version: '3'
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=cpdir
      - MYSQL_USER=checkpoint
      - MYSQL_PASSWORD=123
    volumes:
      - /data/mysql
    healthcheck:
      test: "/usr/bin/mysql --user=checkpoint --password=123--execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
  spring-boot-jpa-app:
    image: cpdir-assignment
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysqldb
    command: sh -c "/wait && /sayhello"
    environment:
      - SPRING_DATASOURCE_URL= jdbc:mysql://mysqldb:3306/cpdir?allowPublicKeyRetrieval=true&useSSL=false
      - WAIT_HOSTS=mysql:3306
      - DATABASE_HOST=mysqldb
      - DATABASE_USER=checkpoint
      - DATABASE_PASSWORD=123
      - DATABASE_NAME=cpdir
      - DATABASE_PORT=3306
    volumes:
      - /data/cpdir-assignment

